#cloud-config

hostname: $HOSTNAME
users:
  - name: $USER
    passwd: $PASSWORD
    groups:
      - sudo
      - docker

write_files:
  - path: /etc/sysctl.d/vm.conf
    permissions: 0644
    owner: root:root
    content: |
      vm.swappiness=0
  - path: /etc/systemd/journald.conf
    permissions: 0644
    owner: root:root
    content: |
      [Journal]
      SystemMaxUse=50M
      RuntimeMaxUse=50M

coreos:
  update:
    group: $CHANNEL
    reboot-strategy: off
  units:
    - name: docker.service
      command: start
    - name: 00-eth0.network
      runtime: true
      content: |
        [Match]
        Name=eth0

        [Network]
        DNS=$DNS
        Address=$PRIVATE_IPV4/24
        Gateway=$GATEWAY
    - name: settimezone.service
      command: start
      content: |
        [Unit]
        Description=Set the timezone

        [Service]
        ExecStart=/usr/bin/timedatectl set-timezone $TIMEZONE
        RemainAfterExit=yes
        Type=oneshot
